### ISSUE TITLE
Make the same but for GNU Octave ?

### ISSUE THREAD

**Issue by Naereen** [tushortz/Matlab-Completions#1]
Hi,

First, who, thanks! Simple to use but great project!
It works quite well :clap: !

Second, from that work it will probably easy to make a similar package but for [GNU Octave](https://www.gnu.org/software/octave/) (a free & open source MATLAB clone), do you think you could try to?
Here in Octave's doc there is a [function index](https://www.gnu.org/software/octave/doc/interpreter/Function-Index.html#Function-Index), and [official package repositories](http://octave.sourceforge.net/packages.php).

Thanks in advance!
(and if I can assist, please ask)

**Comment by tushortz** [comment]
It is possible @Naereen Just some more information. 
- Is it for sublime text
- what is octave file format. i'm guessing `.m` or `.matlab`

and thanks again for the information

**Comment by Naereen** [comment]
- Yes, for ST2 or ST3 exactly as your Matlab-completions package,
- File format is `.m` ([for MATLAB compatibility](https://www.gnu.org/software/octave/doc/interpreter/Introduction-to-Function-and-Script-Files.html#Introduction-to-Function-and-Script-Files)).

**Comment by tushortz** [comment]
OK, Thanks. I'll look into it. ATM, I might just make functions but feel free to contribute in any way @Naereen

**Comment by tushortz** [comment]
@Naereen It's not yet available on package control but a v1.0.0 is available on my Repo. So feel free to use it for the main time.

Just go on Sublime text --> Preference --> Package control --> Add repository --> then paste the following link into the text box.

<a href="https://github.com/tushortz/GNU-Octave-Completions">GNU Octave Completions</a>

Then go back to Install package and search `GNU Octave Completions`.

**Comment by Naereen** [comment]
Great, I will try it during the next couple of days and let you know if anything can be improved.

Bravo :hand: for your reactivity!
